#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

# 设置默认主题为argon
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# 切换opkg源
sed -i 's,downloads.openwrt.org,mirrors.pku.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# 设置LAN口DNS
uci set network.lan.dns='127.0.0.1'
uci commit network
/etc/init.d/network restart

# 默认wan口防火墙打开
uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

# 设置主机名映射，解决安卓原生TV首次连不上网的问题
uci add dhcp domain
uci set "dhcp.@domain[-1].name=time.android.com"
uci set "dhcp.@domain[-1].ip=203.107.6.88"
uci commit dhcp

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit

# Docker换源
uci add_list dockerd.globals.registry_mirrors="https://docker.m.daocloud.io"
uci commit dockerd

### 无线设置
# 删除现有无线配置
uci -q del wireless.default_radio2
uci -q del wireless.default_radio1
uci -q del wireless.default_radio0
uci -q del wireless.wifinet0
uci -q del wireless.wifinet1
uci -q del wireless.wifinet2

# 配置 5GHz 无线接口 (wifinet0)
uci -q set wireless.wifinet0=wifi-iface
uci -q set wireless.wifinet0.device='radio0'
uci -q set wireless.wifinet0.mode='ap'
uci -q set wireless.wifinet0.ssid='ZeroWrt_5G'
uci -q set wireless.wifinet0.encryption='none'
uci -q set wireless.wifinet0.network='lan'

# 配置 5GHz 无线电 (radio0)
uci -q set wireless.radio0.htmode='VHT80'
uci -q set wireless.radio0.channel='36'   # 你可以选择合适的频道
uci -q set wireless.radio0.country='AU'   # 根据需要更改国家
uci -q set wireless.radio0.cell_density='3'
uci -q set wireless.radio0.disabled=0     # 启用 radio0

# 配置 2.4GHz 无线接口 (wifinet1)
uci -q set wireless.wifinet1=wifi-iface
uci -q set wireless.wifinet1.device='radio1'
uci -q set wireless.wifinet1.mode='ap'
uci -q set wireless.wifinet1.ssid='ZeroWrt_2.4G'
uci -q set wireless.wifinet1.encryption='none'
uci -q set wireless.wifinet1.network='lan'

# 配置 2.4GHz 无线电 (radio1)
uci -q set wireless.radio1.htmode='HT40'
uci -q set wireless.radio1.channel='1'    # 你可以选择合适的频道
uci -q set wireless.radio1.country='AU'   # 根据需要更改国家
uci -q set wireless.radio1.cell_density='3'
uci -q set wireless.radio1.disabled=0     # 启用 radio1

# 提交更改并应用
uci commit wireless

exit 0
